name: Sync changes to GitLab

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    if: (github.repository == 'awesome-scripts/awesome-userscripts')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout awesome-scripts/awesome-userscripts
        uses: actions/checkout@v5
        with:
          repository: awesome-scripts/awesome-userscripts
          path: awesome-scripts/awesome-userscripts
          fetch-depth: 0

      - name: Push changes to gitlab.com/awesome-scripts/awesome-userscripts
        run: |
          cd ${{ github.workspace }}/awesome-scripts/awesome-userscripts
          git push --force https://oauth2:${{ secrets.GITLAB_SYNC_PAT }}@gitlab.com/awesome-scripts/awesome-userscripts.git master
